export enum BudgetRequestStatus {
  PENDING_DEPARTMENT_APPROVAL = 'PENDING_DEPARTMENT_APPROVAL',
  PENDING_FINANCE_APPROVAL = 'PENDING_FINANCE_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
